
    <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Invoice</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Invoice</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          
    <div class="col-12">
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Generated Invoice</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="invoiceTable" class="table table-bordered table-hover">
                  <thead>
                    <th>INVOICE NUMBER</th>
                    <th>GENERATED BY</th>
                    <th>DATE ADDED</th>
                    <th>ACTION</th>
                  </thead>
                  <tbody>
                  
                </table>
              </div>
            </div>
        </div>
</div>
</section>
